// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateProjectInput struct {
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Environment *string `json:"environment,omitempty"`
}

type Mutation struct {
}

type Project struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Environment string `json:"environment"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Query struct {
}
