package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"time"

	"github.com/Abhishek260305/HookForge/services/graphql-gateway/graph/model"
	"github.com/Abhishek260305/HookForge/services/graphql-gateway/internal/controlplane"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	env := "dev"
	if input.Environment != nil && *input.Environment != "" {
		env = *input.Environment
	}
	p, err := r.ControlPlane.CreateProject(ctx, controlplane.CreateInput{
		Name:        input.Name,
		Slug:        input.Slug,
		Environment: env,
	})
	if err != nil {
		return nil, err
	}
	return mapProject(p), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]*model.Project, error) {
	items, err := r.ControlPlane.ListProjects(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Project, 0, len(items))
	for _, p := range items {
		out = append(out, mapProject(p))
	}
	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)

func mapProject(p controlplane.Project) *model.Project {
	return &model.Project{
		ID:          p.ID,
		Name:        p.Name,
		Slug:        p.Slug,
		Environment: p.Environment,
		CreatedAt:   p.CreatedAt.UTC().Format(time.RFC3339),
		UpdatedAt:   p.UpdatedAt.UTC().Format(time.RFC3339),
	}
}
